### ISSUE TITLE
Rename action in gts file causes the `default` of a default export to also get renamed.

### ISSUE THREAD

**Issue by NullVoxPopuli** [typed-ember/glint#339]
For example,
given this export:

```ts
export default State as unknown as HelperLike<{ Args: {}, Return: State}>;
```

And this import
```ts
import state from 'limber/helpers/state';
```

if I do a "rename" on `state` on the import to `State` it changes the `default` to `State`, making my export line be `export State State`.

This is in a `.gts` file with this .glintrc.yml config:

```yml
environment:
  - ember-loose
  - ember-template-imports
include:
  - 'app/**'
```
